### ISSUE TITLE
SWVXX would cause 500 error (DivisonByZeroError)

### ISSUE THREAD

**Issue by mzy2240** [investbrainapp/investbrain#95]
Adding the money market fund SWVXX would cause 500 server error

**Comment by mzy2240** [comment]
No error messages in the log by the way

**Comment by mzy2240** [comment]
Seems to be caused by DivisonByZeroError

![Image](https://github.com/user-attachments/assets/efac8630-7c2e-40e1-a36d-cafbb0b573d6)

**Comment by hackeresq** [comment]
Should be resolved with the changes to this component in #88.  Can you give v1.2.0 a shot?  

Pretty confident this resolves the issue. If not, feel free to re-open.

**Comment by theglassprison** [comment]
I just received this same error on 10/23/25.

I'm self-hosted on docker.

**Comment by theglassprison** [comment]
Hello, Sorry for the delayed response. 

I just pulled the latest docker image.  Running on a fully up to date Ubuntu and docker install.   I am still getting the error message

<img width="506" height="577" alt="Image" src="https://github.com/user-attachments/assets/14a69808-dd90-4247-8361-220d4177ed4f" />
